In [125]:
import pandas as pd
import numpy as np
import seaborn as sns

expenses = pd.read_excel (r'C:\Users\LAKSHYA\Downloads\STRBI_Table_No._02___Earnings_and_Expenses_of_Scheduled_Commercial_Banks.xlsx',sheet_name='EXPENSES')
returns = pd.read_excel (r'C:\Users\LAKSHYA\Downloads\STRBI_Table_No._02___Earnings_and_Expenses_of_Scheduled_Commercial_Banks.xlsx',sheet_name='Returns')

In [126]:
expenses.replace('-',np.nan, inplace=True)
Y=returns.iloc[:,:]

expenses=pd.concat([expenses,Y],axis=1)

In [128]:
expenses

,Banks,Interest on deposits,Interest on RBI/ Inter - bank borrowings,Others,Payments to and provisions for employees,"Rent, taxes and lighting",Printing and stationery,Advertisement and publicity,Depreciation on bank's property,"Directors' fees, allowances and expenses",Auditors' fees and expenses,Law charges,"Postage, telegrams, telephones, etc",Repairs and maintenance,Insurance,Other expenditure,Provisions and Contingencies,Total income
0,BANK OF BARODA,37564.403900,1863.767900,2257.864100,11445.530300,1505.920100,126.301800,87.085600,1314.541700,1.22460,73.866300,164.082800,193.794800,1109.636500,1353.871300,3167.800200,19800.849200,82859.499300
1,BANK OF INDIA,24482.289402,1155.891038,691.422711,6472.989995,751.822917,64.668211,7.543886,372.203917,0.42946,80.291636,27.464624,177.621811,60.036252,699.416736,2124.616914,8711.919418,48040.927628
2,BANK OF MAHARASHTRA,6525.948300,49.650600,395.469300,2255.210400,218.233200,17.681500,39.287400,188.111200,0.33460,19.591800,18.358300,56.695500,168.256200,198.671400,384.625700,3407.432700,14493.809700
3,CANARA BANK,42096.959900,1057.893300,2022.770500,12689.959400,1120.147900,133.620900,42.135800,820.169000,0.82320,116.233900,83.835200,109.872500,542.261400,1069.446300,2609.678600,17451.691900,84526.760100
4,CENTRAL BANK OF INDIA,13994.073500,3.256400,487.859900,4141.306300,494.080700,26.540000,4.786400,292.318700,0.53790,28.443100,15.286700,96.994900,116.616200,438.079500,1127.242600,5517.608900,25897.447100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1489,SHINHAN BANK,1.233300,0.131200,1.519300,1.197200,1.009800,0.055400,0.012200,0.263500,NaN,0.018000,0.004600,0.123100,0.215900,0.098900,1.412600,4.512900,17.590800
1490,SOCIETE GENERALE,19.845100,1.718800,0.002000,7.540700,1.204400,0.120100,0.009600,3.260100,NaN,0.027800,0.043300,1.076000,0.518400,0.459300,2.316700,-3.896700,49.476300
1491,SONALI BANK,0.668200,NaN,0.138100,1.600400,0.562000,0.051200,0.017300,0.037500,0.00100,0.025300,0.013500,0.221100,0.011800,0.042100,0.424400,1.068500,6.289500
1492,STANDARD CHARTERED BANK,700.369900,177.674100,229.403700,285.777600,43.818600,28.476900,39.883100,26.838000,NaN,0.409900,21.577300,48.101200,77.191700,16.107800,253.995500,467.166300,3018.382300
1493,UFJ BANK,1.441700,0.012500,0.535100,2.108100,1.677800,0.124700,0.006400,0.562500,NaN,0.026500,0.019000,0.071100,0.289100,0.009900,1.047500,6.650900,21.398400

In [129]:
expenses_missing=expenses.isna()
expenses_missing.mean()*100

Banks                                        0.000000
Interest on deposits                         1.874163
Interest on RBI/ Inter - bank borrowings     5.354752
Others                                      18.607764
Payments to and provisions for employees     0.334672
Rent, taxes and lighting                     0.066934
Printing and stationery                      0.066934
Advertisement and publicity                  3.480589
Depreciation on bank's property              0.200803
Directors' fees, allowances and expenses    40.495315
Auditors' fees and expenses                  0.133869
Law charges                                  4.685408
Postage, telegrams, telephones, etc          0.200803
Repairs and maintenance                      0.669344
Insurance                                    0.669344
Other expenditure                            0.000000
Provisions and Contingencies                 0.000000
Total income                                 0.000000
dtype: float64

In [130]:
expenses.drop(["Directors' fees, allowances and expenses","Others"],axis=1,inplace=True)

In [131]:
expenses.dropna(inplace=True)

In [135]:
Y=expenses.iloc[:,-1].values
X=np.array(expenses['Interest on deposits']).reshape(-1,1)

array([[3.76e+04],
       [2.45e+04],
       [6.53e+03],
       ...,
       [1.98e+01],
       [7.00e+02],
       [1.44e+00]])

In [136]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)

In [138]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)
print(regressor.score(x_test,y_test))
print(regressor.coef_)

0.9681077086698848
[2.]

In [139]:
Y=expenses.iloc[:,-1].values
X=np.array(expenses['Interest on RBI/ Inter - bank borrowings']).reshape(-1,1)
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)
regressor=LinearRegression()
regressor.fit(x_train,y_train)
print(regressor.score(x_test,y_test))
print(regressor.coef_)

0.6297609374920138
[23.78]

In [140]:
Y=expenses.iloc[:,-1].values
X=np.array(expenses['Payments to and provisions for employees']).reshape(-1,1)
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)
regressor=LinearRegression()
regressor.fit(x_train,y_train)
print(regressor.score(x_test,y_test))
print(regressor.coef_)

0.9050472620557135
[7.86]

In [141]:
Y=expenses.iloc[:,-1].values
X=np.array(expenses['Provisions and Contingencies']).reshape(-1,1)
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)
regressor=LinearRegression()
regressor.fit(x_train,y_train)
print(regressor.score(x_test,y_test))
print(regressor.coef_)

0.9004219758865829
[4.48]

In [150]:
Y=expenses.iloc[:,-1].values
X=np.array(expenses['Advertisement and publicity']).reshape(-1,1)
f = lambda x: x ** 2

X_2 = f(X)
X=np.concatenate((X,X_2),axis=1)
f = lambda x: x ** 3

X_3 = f(X)
X=np.concatenate((X,X_3),axis=1)


x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)
regressor=LinearRegression()
regressor.fit(x_train,y_train)
print(regressor.score(x_test,y_test))
print(regressor.coef_)

0.35750604026082966
[ 2.83e+02  1.98e-01 -1.08e-03  7.42e-13]

In [151]:
Y=expenses.iloc[:,-1].values
X=np.array(expenses['Rent, taxes and lighting']).reshape(-1,1)
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)
regressor=LinearRegression()
regressor.fit(x_train,y_train)
print(regressor.score(x_test,y_test))
print(regressor.coef_)

0.967353083192635
[55.93]

In [152]:
Y=expenses.iloc[:,-1].values
X=np.array(expenses['Auditors\' fees and expenses']).reshape(-1,1)
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)
regressor=LinearRegression()
regressor.fit(x_train,y_train)
print(regressor.score(x_test,y_test))
print(regressor.coef_)

0.6985397620228282
[853.83]

In [153]:
X_id=np.array(expenses['Interest on deposits']).reshape(-1,1)
X_pc=np.array(expenses['Provisions and Contingencies']).reshape(-1,1)
X_pe=np.array(expenses['Payments to and provisions for employees']).reshape(-1,1)
X=np.concatenate((X_id,X_pc,X_pe),axis=1)
Y=expenses.iloc[:,-1].values
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)
regressor=LinearRegression()
regressor.fit(x_train,y_train)
print(regressor.score(x_test,y_test))
print(regressor.coef_)

0.9771801109127665
[1.35 0.85 1.31]